################################################################################
# training parameters
################################################################################
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 100
  lr: 0.001              # sgd learning rate
  wup_epochs: 0.01       # warmup during first XX epochs (can be float)
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 16          # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  show_scans: False      # show scans during training
  workers: 4            # number of threads to get data

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "squeezesegV2"  # ['squeezeseg', 'squeezesegV2', 'darknet']
  input_depth:
    range: True
    xyz: True
    remission: True
  dropout: 0.01
  OS: 16 # output stride (only horizontally)
  bn_d: 0.01
  train: True # train backbone?
  extra: False

################################################################################
# decoder parameters
################################################################################
decoder:
  name: "squeezesegV2"
  dropout: 0.01
  bn_d: 0.01
  train: True # train decoder?
  extra: False # nothing to add for this decoder, otherwise this is a dict

################################################################################
# classification head parameters
################################################################################
head:
  name: "segmentation"
  train: True
  dropout: 0.01

################################################################################
# postproc parameters
################################################################################
post:
  CRF: 
    use: True
    train: True
    params:
      iter: 3
      lcn_size:
        h: 3
        w: 5
      xyz_coef: 0.1
      xyz_sigma: 0.7
  KNN:
    use: False
    params:
      knn: 5
      search: 5
      sigma: 1.0 
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -18
    min_w_angle_degree: -40
    max_w_angle_degree: 40
    img_prop:
      width: 512
      height: 64
    img_means: #range,x,y,z,signal
      - 8.687919616699218750
      - 8.074940681457519531
      - 0.1109986454248428345
      - -0.5120335817337036133
      - 0.1504979431629180908
    img_stds: #range,x,y,z,signal
      - 11.59881305694580078 # - 12.32
      - 11.02696895599365234 # - 11.47
      - 4.725028038024902344 # - 6.91
      - 0.7828249931335449219 # - 0.86
      - 0.1753545999526977539 # - 0.16
