experiment_name: "SqueezeSegV2-Filtered-Semantic-debug"
experiment_version: "v1.0"
commit_message: "SqeezeSegV2 fusion model on debug implementation"
working_dir: "/home/mrafaat/AliThesis/lidar-bonnetal/train/tasks/semantic"
dataset: "/raid/ali/AliThesis/FilteredSemanticKitti/dataset/"
arch_cfg: "/home/mrafaat/AliThesis/lidar-bonnetal/train/tasks/semantic/config/filtered-semantic/arch/squeezesegV2_crf.yaml"
data_cfg: "/home/mrafaat/AliThesis/lidar-bonnetal/train/tasks/semantic/config/filtered-semantic/labels/filtered-semantic-remapped-debug.yaml"
log: "/home/mrafaat/AliThesis/lidar-bonnetal/train/tasks/semantic/logs/filtered-semantic-remapped-debug/squeezesegV2_crf"
use_cross_validation: 0
num_cross_folds: 0
cuda: 6
pretrained: None