# This file is covered by the LICENSE file in the root of this project.
name: "filtered-semantic"
labels: 
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "rider"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points, based on seq [0, 2, 3, 4, 5, 6, 9, 10]
  0: 0.026271920305703095
  1: 0.0001836610481126282
  10: 0.04986550346480386
  11: 0.00012019158618916847
  13: 0.0
  15: 0.00043968618040612055
  16: 0.0
  18: 0.002116813326204823
  20: 0.002489014266582607
  30: 0.00015899693384368002
  31: 0.0
  32: 3.8556215187148426e-08
  40: 0.27653571896415086
  44: 0.012841304658803239
  48: 0.12775231466009565
  49: 0.002326674805468472
  50: 0.0931564574672866
  51: 0.06691314587325237
  52: 0.001580030732506636
  60: 7.510750718456514e-05
  70: 0.2491410861601386
  71: 0.007447826975271087
  72: 0.06193553552672879
  80: 0.0034973690306466863
  81: 0.0006895096937798954
  99: 0.011336078915485085
  252: 0.001992680108478445
  253: 0.0002219770284205336
  254: 0.00023922648592272249
  255: 0.0002364593360173679
  256: 0.0
  257: 0.00017733486295922913
  258: 0.00024136487293425587
  259: 1.6970666407758717e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 3     # "motorcycle"
  16: 5     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 4     # "truck"
  20: 5     # "other-vehicle"
  30: 6     # "person"
  31: 7     # "bicyclist" mapped to "rider" ---------------------mapped
  32: 7     # "motorcyclist" mapped to "rider" ---------------------mapped
  40: 9     # "road"
  44: 0    # "parking" mapped to "unlabeled" --------------------------mapped
  48: 11    # "sidewalk"
  49: 0    # "other-ground" mapped to "unlabeled" --------------------------mapped
  50: 13    # "building"
  51: 14    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 9     # "lane-marking" to "road" ---------------------------------mapped
  70: 15    # "vegetation"
  71: 15    # "trunk" to "vegetation" ---------------------------------mapped
  72: 17    # "terrain"
  80: 18    # "pole"
  81: 19    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 7    # "moving-bicyclist" to "rider" ------------------------mapped
  254: 6    # "moving-person" to "person" ------------------------------mapped
  255: 7    # "moving-motorcyclist" to "rider" ------------------mapped
  256: 5    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 5    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 4    # "moving-truck" to "truck" --------------------------------mapped
  259: 5    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 15     # "motorcycle"
  4: 18     # "truck"
  5: 20     # "other-vehicle"
  6: 30     # "person"
  7: 31     # "rider"
  9: 40     # "road"
  11: 48    # "sidewalk"
  13: 50    # "building"
  14: 51    # "fence"
  15: 70    # "vegetation"
  17: 72    # "terrain"
  18: 80    # "pole"
  19: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "rider"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"
  17: False    # "terrain"
  18: False    # "pole"
  19: False    # "traffic-sign"
split: # sequence numbers
  train:
    - 0
    - 2
    - 3
    - 4
    - 5
    - 6
    - 9
    - 10
  valid:
    - 1
    - 7
  test:
    - 8
