################################################################################
# training parameters
################################################################################
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 500
  lr: 0.001              # sgd learning rate
  wup_epochs: 0.01       # warmup during first XX epochs (can be float)
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 64         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  show_scans: False      # show scans during training
  workers: 4            # number of threads to get data
  initialize_seed: True # initialize random number generators
  seed: 27

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "squeezesegV2"  # ['squeezeseg', 'squeezesegV2', 'darknet']
  input_depth:
    range: True
    xyz: True
    remission: True
    rgb: True
    fusion_labels: True
  use_rgb_image: False
  rgb_image_width: 1024 # resize input image to width
  rgb_image_height: 256 # resize input image to height
  dropout: 0.01
  OS: 16 # output stride (only horizontally)
  bn_d: 0.01
  train: True # train backbone?
  extra: False

################################################################################
# decoder parameters
################################################################################
decoder:
  name: "squeezesegV2"
  dropout: 0.01
  bn_d: 0.01
  train: True # train decoder?
  extra: False # nothing to add for this decoder, otherwise this is a dict

################################################################################
# classification head parameters
################################################################################
head:
  name: "segmentation"
  train: True
  dropout: 0.01

################################################################################
# postproc parameters
################################################################################
post:
  CRF: 
    use: True
    train: True
    params:
      iter: 3
      lcn_size:
        h: 3
        w: 5
      xyz_coef: 0.1
      xyz_sigma: 0.7
  KNN:
    use: False
    params:
      knn: 5
      search: 5
      sigma: 1.0 
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -18 #-25 
    img_prop:
      width: 512 #2048
      height: 64
      img_means: #range,x,y,z,signal,r,g,b,label1,label2
        - 8.687919616699218750
        - 8.074940681457519531
        - 0.1109986454248428345
        - -0.5120335817337036133
        - 0.1504979431629180908
        - 48.20320892333984375
        - 48.86914443969726562
        - 47.25114059448242188
        - 0.0
        - 0.0
      img_stds: #range,x,y,z,signal,r,g,b,label1,label
        - 11.59881305694580078
        - 11.02696895599365234
        - 4.725028038024902344
        - 0.7828249931335449219
        - 0.1753545999526977539
        - 73.22473144531250000
        - 72.42098999023437500
        - 70.40472412109375000
        - 1.0
        - 1.0
    # img_means: #range,x,y,z,signal,r,g,b,label1,label2
    #   - 8.7062 #12.12
    #   - 8.0931 #10.88
    #   - 0.1464 #0.23
    #   - -0.5170 #-1.04
    #   - 0.1506 #0.21
    #   - 47.5783
    #   - 48.3181
    #   - 46.9482
    #   - 0.0
    #   - 0.0
    # img_stds: #range,x,y,z,signal,r,g,b,label1,label2
    #   - 11.5592 #12.32
    #   - 10.9987 #11.47
    #   - 4.6943 #6.91
    #   - 0.7859 #0.86
    #   - 0.1748 #0.16
    #   - 72.0980
    #   - 71.4049
    #   - 69.6462
    #   - 1.0
    #   - 1.0
